version: "3.8"

services:
  backend:
    build:
      context: ./
    container_name: backend-java
    #ports:
    #  - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/backend_java
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - backend-java-network
 
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend_java
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-java-network
  dev:
    image: maven:3.8.5-openjdk-17
    container_name: backend-java-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - backend-java-network

volumes:
  pgdata:

networks:
  backend-java-network:
