version: '3'

services:
  backend-php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: app-laravel
    ports:
      - '81:80'
      - '6001:6001'
      - '6006:6006'
    volumes:
      - ./public:/var/www/html
      - ./:/var/www:rw
    environment:
      APP_ENV: development
    depends_on:
      #- pgsql
      - redis
    networks:
      - laravel
      
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

#pgsql:
#    image: postgres:13
#    container_name: pgsql.laravel
#   working_dir: /data/pgsql
#    ports:
#     - "5432:5432"
#    environment:
#      POSTGRES_USERNAME: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#    volumes:
#      - pgsql_data:/var/lib/postgresql/data
#    networks:
#      - laravel

#volumes:
#  pgsql_data:
#    external: true
#    name: itarget_pgsql_data      