version: '3.9'

services:
  backend-javascript:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_nestjs
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres-backend-javascript
      - rabbitmq
    command: npm run start:dev
    networks:
      - backend-javascript-network
      - rabbitmq-network
  postgres-backend-javascript:
    image: postgres:15
    container_name: postgres-backend-javascript
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend_javascript
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-javascript-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'   # Porta do protocolo AMQP
      - '15672:15672' # Porta do painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq-network
      
volumes:
  pgdata:

networks:
  backend-javascript-network:
  rabbitmq-network: